adds mock-redux-episode-2
angular-bbs/user-ui pull request #38
Opened 2016-11-08 10:33 UTC by rxjs-space

2016-11-18 09:32 UTC, asnowwolf commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +现实生活中，`state`的内容要复杂的多，而且除了改变`state`，我们还要处理`side effects`，比如更新`dom`、发送`ajax`请求等等。
side effects最好用汉语，这个不是国内的常用单词

2016-11-18 09:34 UTC, asnowwolf commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +  **应用RxJS，在改变`state`的同时，我们可以很直接的处理`side effects`，不需要像Redux那样使用`Thunk Middleware`。**
Thunk Middleware 需要解释一下，我们要假设读者并没有多少Redux背景知识

2016-11-18 09:37 UTC, asnowwolf commented on src/app/_shared/api/articles/mock-redux-with-rxjs/_index.md
>  水平所限，难免有错漏，请大家多指教。另外，我写的比较啰嗦，请大家多包涵。
在文字表达方面确实还有提升的空间，不过目前可以优先关注内容。

2016-11-18 09:38 UTC, asnowwolf commented on src/app/_shared/api/articles/mock-redux-with-rxjs/_index.md
>  2. `Observable`：定义在某个时点通过调用`observer.callback(v)`（比如`observer.next(v)`）将数据`v`推送给`observer`；
`callback`和`next`之间是什么关系？

2016-11-18 09:40 UTC, asnowwolf commented on src/app/_shared/api/articles/mock-redux-with-rxjs/_index.md
>    `Observable`不会自动运行，而是要通过`subscribe`方法来启动，
这句话只在Cold型Observable才正确，对于Hot型的我印象中是不管有没有订阅的。

2016-11-18 10:21 UTC, asnowwolf commented on src/app/_shared/api/articles/mock-redux-with-rxjs/_index.md
>    不同在于Array.prototype.reduce是把Array中所有的数值累积后形成一个值，而Observable.prototype.scan是把当前值和之前的累积值再次累积形成一个值，参见示例：
算法上的区别在哪里？从示例中看不出来。

2016-11-18 10:39 UTC, asnowwolf commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +接下来的部分都是上面代码的具体应用，大家赶时间的话，可以全部跳过。
没看懂……“接下来的部分”是指哪里？

2016-11-18 10:40 UTC, asnowwolf commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +  `Observable`像是一个`Function`，每次运行`sampleObservable$.subscribe(observer)`，都相当于一次`sampleFunction.call()`，是一次独立的运行，单独消耗资源。
单独消耗是指每次都消耗吗？

2016-11-18 10:43 UTC, asnowwolf commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +以`app启动`为例，走一遍流程。
为何要用` `` `符号？

2016-11-18 10:44 UTC, asnowwolf commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +就是这个`GET_ALL_START_handler`：
重要的事情说三遍么……

2016-11-18 11:11 UTC, asnowwolf requested changes
看完了，总体很不错，细节需要改进。多谢投稿！

2016-11-19 13:44 UTC, rxjs-space commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +现实生活中，`state`的内容要复杂的多，而且除了改变`state`，我们还要处理`side effects`，比如更新`dom`、发送`ajax`请求等等。
同意。此处改为：“我们还要处理“副作用（`side effects`）”，比如...”

2016-11-19 13:53 UTC, rxjs-space commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +  **应用RxJS，在改变`state`的同时，我们可以很直接的处理`side effects`，不需要像Redux那样使用`Thunk Middleware`。**
这里改为：“不需要像Redux那样使用中间件（middleware）”。
不想过多解释，容易露怯。
我会加上一个链接到redux middleware的文档，好奇的读者可以看链接。

2016-11-19 13:53 UTC, rxjs-space commented on src/app/_shared/api/articles/mock-redux-with-rxjs/_index.md
>  水平所限，难免有错漏，请大家多指教。另外，我写的比较啰嗦，请大家多包涵。
努力努力，翻滚翻滚。

2016-11-19 13:54 UTC, rxjs-space commented on src/app/_shared/api/articles/mock-redux-with-rxjs/_index.md
>  2. `Observable`：定义在某个时点通过调用`observer.callback(v)`（比如`observer.next(v)`）将数据`v`推送给`observer`；
根据前面第一点“Observer”的说明，observer.next是observer.callback的一种。

2016-11-19 13:58 UTC, rxjs-space commented on src/app/_shared/api/articles/mock-redux-with-rxjs/_index.md
>    `Observable`不会自动运行，而是要通过`subscribe`方法来启动，
这里不想提cold, hot。我觉得cold, hot只有在两个地方会用到：1）广义的Observable，即世间万物，不需要Observable constructor来构建的世间万物；2）测试Observable，会用字符形式的marble diagram来定义hot observable，用来测试subscription的时间点。其他地方暂时不想提。以后可能会专门写个短文和大家探讨。

2016-11-19 14:07 UTC, rxjs-space commented on src/app/_shared/api/articles/mock-redux-with-rxjs/_index.md
>    不同在于Array.prototype.reduce是把Array中所有的数值累积后形成一个值，而Observable.prototype.scan是把当前值和之前的累积值再次累积形成一个值，参见示例：
这段会在实例代码出做出更详尽说明，如下：
    `js
    observable$.scan((accumulated, current) => accumulated + current, 0);
    // 假设observable$推送的第一个数值为1，在推送第一个数值的时候，accumulated是0，即初始值，current是1，返回值是accumulated = accumulated + current即1；  
    // observable$每次推送新的数值，都会有一个新的accumulated数值推送，不需要等到observable$运行结束（即调用observer.complete()）  
    // 类似Array.prototype.reduce，比如：[1, 2, 3].reduce((acc, curr) => acc + curr, 0);  
    // 但是Array.prototype.reduce返回的结果是要把array中的所有数值都积累起来，而Observable.prototype.scan是积累到当前值
`

2016-11-19 14:08 UTC, rxjs-space commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +接下来的部分都是上面代码的具体应用，大家赶时间的话，可以全部跳过。
这里改为：“余下全文都是上面代码的具体应用...”

2016-11-19 14:10 UTC, rxjs-space commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +  `Observable`像是一个`Function`，每次运行`sampleObservable$.subscribe(observer)`，都相当于一次`sampleFunction.call()`，是一次独立的运行，单独消耗资源。
是的。可以参看其后的实例代码。

2016-11-19 14:10 UTC, rxjs-space commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +以`app启动`为例，走一遍流程。
手抖。改成双引号。

2016-11-19 14:10 UTC, rxjs-space commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +就是这个`GET_ALL_START_handler`：
`是的。`

2016-11-21 04:37 UTC, merged

2016-11-21 05:26 UTC, lhtin commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +现实生活中，`state`的内容要复杂的多，而且除了改变`state`，我们还要处理[“副作用（`side effects`）”][]，比如更新`dom`、发送`ajax`请求等等。
一个小建议，在中文里面的英文尽量少用代码格式的标记，比如这行的side effects，dom，ajax，state。因为格式不同，阅读起来体验不是很好。除了必要的，表示代码中的某个变量等才用，可能对阅读体验会更好些。

2016-11-21 06:21 UTC, rxjs-space commented on src/app/_shared/api/articles/timliu/mock-redux-with-rxjs-episode-2-todo-app/_index.md
> +现实生活中，`state`的内容要复杂的多，而且除了改变`state`，我们还要处理[“副作用（`side effects`）”][]，比如更新`dom`、发送`ajax`请求等等。
收到。