新增文章：从ng1到ng2的平滑升级[2]
angular-bbs/user-ui pull request #42
Opened 2016-11-12 05:19 UTC by twincle

新增文章：从ng1到ng2的平滑升级[2]

2016-11-15 04:57 UTC, lhtin commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +不过编写代码我们总希望能够尽可能优化代码。
两个“不过”，有点糊涂了。建议重新表述一下

2016-11-15 05:03 UTC, lhtin commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +> 关于service、factory、provider：相信你在使用ng1的时候一定对这三个概念产生过困惑，网上也有很多相关文章讨论三者之间的差别和联系。但稍微深入研究一下就会知道，这三者本质相同，只是做了不同的语法糖包装。本文以service为例完成升级过程。
”本质相同“这个能否在具体描述下，是指它们都是通过依赖注入的方式吗？

2016-11-15 05:05 UTC, lhtin commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +不过好在这个依赖是通过DI的方式注入到方法中，方法也并没有直接对ng1产生依赖，因此到这里为止，关于`$http`这个依赖就这样处理也无伤大雅。
也就是说`$http`仅仅是一个函数的参数？

2016-11-15 05:08 UTC, lhtin commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +```
markdown的一个用法问题：给代码块加上具体编程语言的标识，方便markdown解释器进行高亮。用法示例，比如是js可以这样：```JavaScript，ts的代码：```TypeScript等

2016-11-15 09:37 UTC, twincle commented
调整部分文句，修正一些代码问题

2016-11-18 11:54 UTC, asnowwolf commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +1. 拆分ng1框架代码和业务代码，并将框架代码集中至一个或几个文件中；
“框架相关”的代码？

2016-11-18 11:56 UTC, asnowwolf commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +> 关于service、factory、provider：在ng1中，我们可以通过`angular.Module`的这三个方法，来创建自己的服务，并将这些组件注册在ng1环境中，今后通过依赖注入的方式在项目中使用。相信你在使用ng1的时候一定对这三个概念产生过困惑，网上也有很多相关文章讨论三者之间的差别和联系。但稍微深入研究一下就会知道，这三者本质相同，只是做了不同的语法糖包装。本文以servi
module小写

2016-11-18 12:05 UTC, asnowwolf commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +简单来说，我们将一个__字符串数组__作为`$inject`属性赋值给一个方法，ng1就会按照数组中的字符串对方法注入依赖，我们来看一下代码：
中文中尽量用*代替_，有些不完善的md处理器需要前后有空格才能识别_。

2016-11-18 12:08 UTC, asnowwolf commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +import User from './user.model';
User的导入方法和其它类不同，容易让读者困惑，建议和别处保持一致或者说明一下为何如此。

2016-11-18 12:10 UTC, asnowwolf commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +如果说service、factory、provider比较类似——至少都可以注入依赖并通过function（es3）或class（typescript）来完成定义，那么value和constant就有点不太一样，因为它们就只是一个值而已啊。
ng2中更彻底的方法是使用useValue，让它仍然继续保持为依赖注入对象。这种写法移除了其依赖注入特性，两者并不等价。当然，如果刻意如此，建议声明一下这只是权宜之计。

2016-11-18 12:17 UTC, asnowwolf requested changes
感谢投稿，稍作修改即可。

2016-11-21 05:35 UTC, lhtin commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +简单来说，我们将一个__字符串数组__作为`$inject`属性赋值给一个方法，ng1就会按照数组中的字符串对方法注入依赖，我们来看一下代码：
雪狼的文字给格式了，我转述一遍：中文中尽量用`*`代替`_`，有些不完善的md处理器需要前后有空格才能识别`_`。

2016-11-21 05:35 UTC, lhtin commented on src/app/_shared/api/articles/270.从ng1到ng2的平滑升级[2]/_index.md
> +简单来说，我们将一个__字符串数组__作为`$inject`属性赋值给一个方法，ng1就会按照数组中的字符串对方法注入依赖，我们来看一下代码：
雪狼的文字给格式了，我转述一遍：中文中尽量用`*`代替`_`，有些不完善的md处理器需要前后有空格才能识别`_`。

2016-11-25 05:14 UTC, merged